package com.mobility.race.ui.drawUtils

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.res.imageResource
import com.mobility.race.R

@Composable
fun bitmapStorage(context: Context): Map<String, ImageBitmap> {
    return mutableMapOf(
        "car1_1" to ImageBitmap.imageResource(R.drawable.car1_1),
        "car1_2" to ImageBitmap.imageResource(R.drawable.car1_2),
        "car1_3" to ImageBitmap.imageResource(R.drawable.car1_3),
        "car1_4" to ImageBitmap.imageResource(R.drawable.car1_4),
        "car2_1" to ImageBitmap.imageResource(R.drawable.car2_1),
        "car2_2" to ImageBitmap.imageResource(R.drawable.car2_2),
        "car2_3" to ImageBitmap.imageResource(R.drawable.car2_3),
        "car2_4" to ImageBitmap.imageResource(R.drawable.car2_4),
        "car3_1" to ImageBitmap.imageResource(R.drawable.car3_1),
        "car3_2" to ImageBitmap.imageResource(R.drawable.car3_2),
        "car3_3" to ImageBitmap.imageResource(R.drawable.car3_3),
        "car3_4" to ImageBitmap.imageResource(R.drawable.car3_4),
        "car4_1" to ImageBitmap.imageResource(R.drawable.car4_1),
        "car4_2" to ImageBitmap.imageResource(R.drawable.car4_2),
        "car4_3" to ImageBitmap.imageResource(R.drawable.car4_3),
        "car4_4" to ImageBitmap.imageResource(R.drawable.car4_4),
        "car5_1" to ImageBitmap.imageResource(R.drawable.car5_1),
        "car5_2" to ImageBitmap.imageResource(R.drawable.car5_2),
        "car5_3" to ImageBitmap.imageResource(R.drawable.car5_3),
        "car5_4" to ImageBitmap.imageResource(R.drawable.car5_4),
        "car6_1" to ImageBitmap.imageResource(R.drawable.car6_1),
        "car6_2" to ImageBitmap.imageResource(R.drawable.car6_2),
        "car6_3" to ImageBitmap.imageResource(R.drawable.car6_3),
        "car6_4" to ImageBitmap.imageResource(R.drawable.car6_4),

        // Updated terrain mappings
        "terrain_000" to ImageBitmap.imageResource(R.drawable.terrain_000),
        "terrain_010" to ImageBitmap.imageResource(R.drawable.terrain_010),
        "terrain_101" to ImageBitmap.imageResource(R.drawable.terrain_101),
        "terrain_102" to ImageBitmap.imageResource(R.drawable.terrain_102),
        "terrain_103" to ImageBitmap.imageResource(R.drawable.terrain_103),
        "terrain_104" to ImageBitmap.imageResource(R.drawable.terrain_104),
        "terrain_105" to ImageBitmap.imageResource(R.drawable.terrain_105),
        "terrain_106" to ImageBitmap.imageResource(R.drawable.terrain_106),
        "terrain_107" to ImageBitmap.imageResource(R.drawable.terrain_107),
        "terrain_108" to ImageBitmap.imageResource(R.drawable.terrain_108),
        "terrain_109" to ImageBitmap.imageResource(R.drawable.terrain_109),
        "terrain_110" to ImageBitmap.imageResource(R.drawable.terrain_110),
        "terrain_111" to ImageBitmap.imageResource(R.drawable.terrain_111),
        "terrain_112" to ImageBitmap.imageResource(R.drawable.terrain_112),
        "terrain_113" to ImageBitmap.imageResource(R.drawable.terrain_113),
        "terrain_201" to ImageBitmap.imageResource(R.drawable.terrain_201),
        "terrain_202" to ImageBitmap.imageResource(R.drawable.terrain_202),
        "terrain_203" to ImageBitmap.imageResource(R.drawable.terrain_203),
        "terrain_204" to ImageBitmap.imageResource(R.drawable.terrain_204),
        "terrain_205" to ImageBitmap.imageResource(R.drawable.terrain_205),
        "terrain_206" to ImageBitmap.imageResource(R.drawable.terrain_206),
        "terrain_207" to ImageBitmap.imageResource(R.drawable.terrain_207),
        "terrain_208" to ImageBitmap.imageResource(R.drawable.terrain_208),
        "terrain_209" to ImageBitmap.imageResource(R.drawable.terrain_209),
        "terrain_210" to ImageBitmap.imageResource(R.drawable.terrain_210),
        "terrain_211" to ImageBitmap.imageResource(R.drawable.terrain_211),
        "terrain_301" to ImageBitmap.imageResource(R.drawable.terrain_301),
        "terrain_302" to ImageBitmap.imageResource(R.drawable.terrain_302),
        "terrain_303" to ImageBitmap.imageResource(R.drawable.terrain_303),
        "terrain_304" to ImageBitmap.imageResource(R.drawable.terrain_304),
        "terrain_305" to ImageBitmap.imageResource(R.drawable.terrain_305),
        "terrain_306" to ImageBitmap.imageResource(R.drawable.terrain_306),
        "terrain_307" to ImageBitmap.imageResource(R.drawable.terrain_307),
        "terrain_308" to ImageBitmap.imageResource(R.drawable.terrain_308),
        "terrain_309" to ImageBitmap.imageResource(R.drawable.terrain_309),
        "terrain_310" to ImageBitmap.imageResource(R.drawable.terrain_310),
        "terrain_311" to ImageBitmap.imageResource(R.drawable.terrain_311),
        "terrain_401" to ImageBitmap.imageResource(R.drawable.terrain_401),
        "terrain_402" to ImageBitmap.imageResource(R.drawable.terrain_402),
        "terrain_403" to ImageBitmap.imageResource(R.drawable.terrain_403),
        "terrain_404" to ImageBitmap.imageResource(R.drawable.terrain_404),
        "terrain_405" to ImageBitmap.imageResource(R.drawable.terrain_405),
        "terrain_406" to ImageBitmap.imageResource(R.drawable.terrain_406),
        "terrain_407" to ImageBitmap.imageResource(R.drawable.terrain_407),
        "terrain_408" to ImageBitmap.imageResource(R.drawable.terrain_408),
        "terrain_409" to ImageBitmap.imageResource(R.drawable.terrain_409),
        "terrain_410" to ImageBitmap.imageResource(R.drawable.terrain_410),
        "terrain_411" to ImageBitmap.imageResource(R.drawable.terrain_411),
        "terrain_500" to ImageBitmap.imageResource(R.drawable.terrain_500)
    )
}